version: 2.0

jobs:
  'lint':
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run tests
          command: yarn lint

  'test':
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run build
          command: yarn test:ci

  'build':
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run build
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - 'lint'
      - 'build'
      - 'test'
